CFLAGS  = -Wall -pedantic -std=c99 -O3 -march=native -mtune=native
LDFLAGS =
BINARY  = mandel
VERSION = 0.1
PREFIX  = /usr/local
OBJECTS = $(BINARY).o

all: $(BINARY)

clean:
	rm -f $(BINARY).o $(BINARY)
